### ISSUE TITLE
Any options for parsing text?

### ISSUE THREAD

**Issue by dmrickey** [educational-resources-and-services/bibletags-data#10]
Do you have any options for parsing text and finding any verses referenced? So if there's text like "Lorem ipsum dolor sit amet, consectetur _John 3:16_ adipiscing elit, sed do eiusmod tempor" then it can find that John 3:16 is referenced in the middle of the text?

**Comment by AndyHubert** [comment]
There is nothing exactly like this available in this repo at the moment. The closest thing is the `getRefsFromPassageStr` function that is exported from `@bibletags/bibletags-ui-helper`.
